# Generated by Django 3.2.3 on 2021-08-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210827_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='skd',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
